services:
  - type: web
    name: virtual-makeup-tryon
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FLASK_ENV
        value: "production"
    healthCheckPath: /
    autoDeploy: false
